### ISSUE TITLE
Align level (and feature) names in output

### ISSUE THREAD

**Issue by orome** [mowispace/react-native-logs#62]
It would be great if there was an option to left align messages when level printing is enabled. As it is the different lengths of level names results in jagged and hard to read output when different levels are interleaved. 

(Feature printing can easily be aligned by just choosing fixed length features, but having the same for fathers would be nice too).

**Comment by alessandro-bottamedi** [comment]
i've ddded the confg option fixedExtLvlLength, allowing for uniform extension and level lengths by adding spaces, ensuring aligned logs. 9f65b36
