### ISSUE TITLE
Bug: function type log arguments are printed as `null`

### ISSUE THREAD

**Issue by pke** [mowispace/react-native-logs#69]
This cost me more than an hour of debugging now.

```ts
function test() {
}

logger.info(test)
```

will log `null` which is confusing. It should log `function` or the functions name.

**Comment by alessandro-bottamedi** [comment]
You are right, in my opinion it should print an empty object:"{}" printing null or the name of the object could be confusing....

**Comment by pke** [comment]
`console.log` prints the type (and name): `function name()`

**Comment by alessandro-bottamedi** [comment]
Fixed in 592e139
