### ISSUE TITLE
Type errors with noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by dansimau** [mowispace/react-native-logs#72]
The following example:

```ts
import {logger} from "react-native-logs";

const f = logger.createLogger();
f.debug("foo");
```

Results in:

```
error TS2722: Cannot invoke an object which is possibly 'undefined'.

 f.debug("foo");
 ~~~~~~~
```

When compiling to TypeScript with `"noUncheckedIndexedAccess": true`:
https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

**Comment by germisi** [comment]
Check [Levels typing](https://www.npmjs.com/package/react-native-logs#:~:text=message%22\)%3B-,Levels,-typing)

**Comment by alessandro-bottamedi** [comment]
I added the suggestion in the readme, thank you.
