### ISSUE TITLE
extensionColors not working on zsh macOS terminal

### ISSUE THREAD

**Issue by strawberry-code** [mowispace/react-native-logs#73]
My configuration is
```javascript
const defaultConfig = {
  levels: {
    sensitive: 0,
    debug: 1,
    network: 2,
    info: 3,
    success: 4,
    warn: 5,
    error: 6,
    mysdk: 7,
  },
  severity: 'sensitive', // ⚠️ Disable it in production!
  transport: [consoleTransport, fileAsyncTransport],
  transportOptions: {
    FS: RNFS,
    fileName: `${formattedTodayDate}.log`,
    colors: {
      sensitive: 'magentaBright',
      debug: 'cyanBright',
      network: 'blueBright',
      info: 'grayBright',
      success: 'greenBright',
      warn: 'yellowBright',
      error: 'redBright',
    },
  },
  extensionColors: {
    CRYPTO: 'yellowBright',
    WELCOME: 'magenta',
    MYSDK: 'cyanBright',
  },
  async: true,
  dateFormat: 'iso',
  printLevel: true,
  printDate: true,
  enabled: true,
};
```

Example usage in my code:
```javascript 
const welcomeLog = log.extend('WELCOME');
```

What I get actually:
![Screenshot 2023-03-11 at 21 21 22](https://user-images.githubusercontent.com/18684103/224509929-40093e4d-777d-4c7c-b6d1-ddb7c4ad6eb9.png)

What I expect:
![Screenshot 2023-03-11 at 21 21 22](https://user-images.githubusercontent.com/18684103/224509972-e84f10b7-4a82-4e90-bbaa-9c9547d5196b.png)

Ie: the extensions CRYPTO and WELCOME should be backgrounded as yellowBright and magenta respectively.

Using: ` "react-native-logs": "^5.0.1"`.

**Comment by alessandro-bottamedi** [comment]
I can't reproduce the issue; feel free to reopen if someone else experiences the same behavior.
