### ISSUE TITLE
how we can access log.txt file in iOS device

### ISSUE THREAD

**Issue by codemap01** [mowispace/react-native-logs#76]
We are able to create a `log.txt` file in Android using RNFS but in iOS how we can access the `log.txt` file?
@alessandro-bottamedi , @shahanshah87,@Rankarusu, @creambyemute

**Comment by creambyemute** [comment]
@codemap01 I'm sorry but we are no longer using react-native-logs.

We've created our own logger with mobx, mobx-utils (chunkProcessor) and RNFS/fetch-blob

**Comment by codemap01** [comment]
@creambyemute can you please suggest any other good React Native library for logging also compatible with both platform Android and iOS

**Comment by jasmeet447** [comment]
I think [React-native-file-logger](https://www.npmjs.com/package/react-native-file-logger) can be a good alternative @codemap01

**Comment by daksh23** [comment]
Yes not able to access file using expo in both platform ios and android

**Comment by alessandro-bottamedi** [comment]
I added a demo file (`demo/ComponentReadLogsRN.tsx`) for implementing a simple component to display log files in a React Native app, it might be helpful for you.
