### ISSUE TITLE
today date formatting is incorrectly described in the docs

### ISSUE THREAD

**Issue by willryanuk** [mowispace/react-native-logs#84]
In the docs for the fileAsyncFileTransport, it states the date format like this:

```If you want a new file to be created every day you can use {date-today} in the fileName: app_logs_{date-today}.log -> app_logs_DD-MM-YYYY.log.```

But in reality, {date-today} is in fact:
D-M-YYYY

I can also see this in the code:
fileName = fileName.replace("{date-today}", `${d}-${m}-${y}`);

**Comment by alessandro-bottamedi** [comment]
You right, thanks, doc fixed.
