### ISSUE TITLE
Date format with using {date-today}

### ISSUE THREAD

**Issue by BohdanBida** [mowispace/react-native-logs#92]
When I describe a file name, I want a separate file to be created every day but with date using my format (e.g. using usa format instead of default)

How to do it? I didn't find this in the documentation and I think it's currently not possible.

**Comment by codejudas** [comment]
+1 Honestly would just be nice if it used the format `YYYY-MM-DD` instead of `DD-MM-YYYY` so that files can be sorted lexicographically in the days they cover.

**Comment by alessandro-bottamedi** [comment]
in v 5.2.0 Added fileNameDateType option to the file transport for selecting the date format: `eu` "DD-MM-YYYY", `us` "MM-DD-YYYY", `iso` "YYYY-MM-DD"
