### ISSUE TITLE
Logs are not showing color on metro bundler for React native

### ISSUE THREAD

**Issue by CoryWritesCode** [mowispace/react-native-logs#95]
Been playing around with your logger but it seems like it's not applying the colors correctly.

![image](https://github.com/mowispace/react-native-logs/assets/34924300/567ba0c1-1a2d-442e-ba6d-d4baf824fdfa)

![image](https://github.com/mowispace/react-native-logs/assets/34924300/c68a60ea-00dc-4287-b84d-a4311e1b92ba)

Maybe I'm misconfiguring it?

![image](https://github.com/mowispace/react-native-logs/assets/34924300/31783702-699b-483b-96c0-ed0c68e9cf38)

**Comment by alessandro-bottamedi** [comment]
try to configure transport options: 

```javascript
transportOptions: {
    colors: {
      info: "blueBright",
      warn: "yellowBright",
      error: "redBright",
    },
    extensionColors: {
      root: "magenta",
      home: "grey",
      user: "blue",
    },
  },
```
