### ISSUE TITLE
Request for a new feature

### ISSUE THREAD

**Issue by ChDevThinker** [mowispace/react-native-logs#99]
Hello,

I'm using react-native-logs since few months and it's really useful. Thank you.
I'm looking for a way to display in logs the name and/or function of the trigger log.

For example, If I put a log in SomeFile.tsx. I would like to see in my log message this : ` LOG  5:06:39 PM | INFO : SomeFile :  my messge`.

An other example, if I put a log in myFunction() that is used in SomeFile.tsx. I would like to see in my log message this : ` LOG  5:06:39 PM | INFO : SomeFile.myFunction() :  my messge`.

I know that namespaces can help me but, I have to declare it manually and if my code change I have to change the namespaces.

Best regards.

**Comment by ChDevThinker** [comment]
Hello,
It's may be the wrong place to talk about new features ?

**Comment by pke** [comment]
Can't you use `__filename` or something like as the namespace and remove the file extension when extending the logger?

@alessandro-bottamedi could you maybe enable discussions here? This this would be Q&A type of discussion and not clutter the issues tracker? Thanks!

**Comment by alessandro-bottamedi** [comment]
i've open a discussione here: #106 Thanks!
